// Express
import express from "express";
import http from "http";
import bodyParser from "body-parser";
import path from "path";

// Swagger
import swaggerUi from "swagger-ui-express";
import yaml from "yamljs";

// Logging
import Logger from "./Logger";

// Properties
import properties from "../properties.js";

// Security
import cors from "cors";
import helmet from "helmet";

// Controllers
import SecurityController from "../controllers/SecurityController";

// Start Import Controllers

// Database
import Database_Chytraskola_db from "./Database_Chytraskola_db.js";

// Controllers
import UserController from "../controllers/Chytraskola_db/UserController";
import DochadzkaController from "../controllers/Chytraskola_db/DochadzkaController";
import OdboryController from "../controllers/Chytraskola_db/OdboryController";
import PredmetyController from "../controllers/Chytraskola_db/PredmetyController";
import RodiciaController from "../controllers/Chytraskola_db/RodiciaController";
import RozvrhController from "../controllers/Chytraskola_db/RozvrhController";
import SkolaController from "../controllers/Chytraskola_db/SkolaController";
import SkupinaController from "../controllers/Chytraskola_db/SkupinaController";
import Spravy_archivController from "../controllers/Chytraskola_db/Spravy_archivController";
import Spravy_skupinyController from "../controllers/Chytraskola_db/Spravy_skupinyController";
import Spravy_uzivateliaController from "../controllers/Chytraskola_db/Spravy_uzivateliaController";
import StudentController from "../controllers/Chytraskola_db/StudentController";
import TriedyController from "../controllers/Chytraskola_db/TriedyController";
import UcitelController from "../controllers/Chytraskola_db/UcitelController";
import UdalostController from "../controllers/Chytraskola_db/UdalostController";
import UzivatelController from "../controllers/Chytraskola_db/UzivatelController";
import Vyucovanie_casController from "../controllers/Chytraskola_db/Vyucovanie_casController";
import ZadaniaController from "../controllers/Chytraskola_db/ZadaniaController";
import ZnamkyController from "../controllers/Chytraskola_db/ZnamkyController";

// End Import Controllers


class Server {
  constructor() {
    this.app = express();
  }

  /**
   * Start the server
   * @returns {Promise<void>}
   */
  async init() {
    Logger.info(
      "\r\n\r\n-----------------------------------\r\n\r\nStarting chytraskola \r\nGenerated by\r\n\r\n   _____ _          __  __      _     _           \r\n  / ____| |        / _|/ _|    | |   | |          \r\n | (___ | | ____ _| |_| |_ ___ | | __| | ___ _ __ \r\n  \\___ \\| |/ / _` |  _|  _/ _ \\| |/ _` |/ _ \\ '__|\r\n  ____) |   < (_| | | | || (_) | | (_| |  __/ |   \r\n |_____/|_|\\_\\__,_|_| |_| \\___/|_|\\__,_|\\___|_|   \r\n\r\nFor more documentation please visit https://skaffolder.com/#/documentation\r\n\r\n-----------------------------------\r\n\r\n"
    );

    // Start Init Database
		Database_Chytraskola_db.init();
 // End Init Database

    // Add parser
    this.app.use(bodyParser.json());
    this.app.use(bodyParser.urlencoded({ extended: true }));
    this.app.use(Logger.expressMiddleware);

    // Securitiy
    this.app.use(helmet());
    this.app.use(cors());

    // Swagger
    const swaggerDocument = yaml.load("./swagger.yaml");
    this.app.use(
      properties.api + "/docs",
      swaggerUi.serve,
      swaggerUi.setup(swaggerDocument)
    );

    // Redirect frontend
    this.app.use("*", (req, res, next) => {
      if (req.originalUrl) {
        let url = req.originalUrl;
        if (!url.startsWith("/api/") && url.indexOf(".") == -1) {
          res
            .status(200)
            .sendFile(
              path.resolve(
                __dirname +
                  "//..//" +
                  properties.publicPath.replace(/\//g, "//") +
                  "//index.html"
              )
            );
        } else {
          next();
        }
      } else {
        next();
      }
    });
    
    // Start App Server
    const server = http.Server(this.app);
    this.app.use(express.static(properties.publicPath));

    await server.listen(properties.port);
    Logger.info("Server started on port " + properties.port);
    Logger.info(
      "Swagger docs at http://localhost:" +
        properties.port +
        properties.api +
        "/docs"
    );

    // Import controllers
    const router = express.Router();
    SecurityController.init(router);

    // Start Init Controllers
		UserController.init(router);
		DochadzkaController.init(router);
		OdboryController.init(router);
		PredmetyController.init(router);
		RodiciaController.init(router);
		RozvrhController.init(router);
		SkolaController.init(router);
		SkupinaController.init(router);
		Spravy_archivController.init(router);
		Spravy_skupinyController.init(router);
		Spravy_uzivateliaController.init(router);
		StudentController.init(router);
		TriedyController.init(router);
		UcitelController.init(router);
		UdalostController.init(router);
		UzivatelController.init(router);
		Vyucovanie_casController.init(router);
		ZadaniaController.init(router);
		ZnamkyController.init(router);
		 // End Init Controllers

    this.app.use("/", router);
  }
}

export default new Server();
