
// INSERT HERE YOUR CUSTOM CONSTANTS




// START CRUD CONSTANTS

// USER
export const CHANGEPASSWORD_USER_SUCCESS = "CHANGEPASSWORD_USER_SUCCESS";
export const CREATE_USER_SUCCESS = "CREATE_USER_SUCCESS";
export const DELETE_USER_SUCCESS = "DELETE_USER_SUCCESS";
export const GET_USER_SUCCESS = "GET_USER_SUCCESS";
export const LIST_USER_SUCCESS = "LIST_USER_SUCCESS";
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";

// DOCHADZKA
export const CREATE_DOCHADZKA_SUCCESS = "CREATE_DOCHADZKA_SUCCESS";
export const DELETE_DOCHADZKA_SUCCESS = "DELETE_DOCHADZKA_SUCCESS";
export const FINDBY_TRIEDY_DOCHADZKA_SUCCESS = "FINDBY_TRIEDY_DOCHADZKA_SUCCESS";
export const FINDBY_UCITEL_DOCHADZKA_SUCCESS = "FINDBY_UCITEL_DOCHADZKA_SUCCESS";
export const GET_DOCHADZKA_SUCCESS = "GET_DOCHADZKA_SUCCESS";
export const LIST_DOCHADZKA_SUCCESS = "LIST_DOCHADZKA_SUCCESS";
export const UPDATE_DOCHADZKA_SUCCESS = "UPDATE_DOCHADZKA_SUCCESS";

// ODBORY
export const CREATE_ODBORY_SUCCESS = "CREATE_ODBORY_SUCCESS";
export const DELETE_ODBORY_SUCCESS = "DELETE_ODBORY_SUCCESS";
export const GET_ODBORY_SUCCESS = "GET_ODBORY_SUCCESS";
export const LIST_ODBORY_SUCCESS = "LIST_ODBORY_SUCCESS";
export const UPDATE_ODBORY_SUCCESS = "UPDATE_ODBORY_SUCCESS";

// PREDMETY
export const FINDBY_TRIEDY_PREDMETY_SUCCESS = "FINDBY_TRIEDY_PREDMETY_SUCCESS";
export const FINDBY_UCITEL_PREDMETY_SUCCESS = "FINDBY_UCITEL_PREDMETY_SUCCESS";
export const LIST_PREDMETY_SUCCESS = "LIST_PREDMETY_SUCCESS";

// RODICIA
export const CREATE_RODICIA_SUCCESS = "CREATE_RODICIA_SUCCESS";
export const DELETE_RODICIA_SUCCESS = "DELETE_RODICIA_SUCCESS";
export const FINDBY_STUDENT_RODICIA_SUCCESS = "FINDBY_STUDENT_RODICIA_SUCCESS";
export const GET_RODICIA_SUCCESS = "GET_RODICIA_SUCCESS";
export const LIST_RODICIA_SUCCESS = "LIST_RODICIA_SUCCESS";
export const UPDATE_RODICIA_SUCCESS = "UPDATE_RODICIA_SUCCESS";

// ROZVRH
export const CREATE_ROZVRH_SUCCESS = "CREATE_ROZVRH_SUCCESS";
export const DELETE_ROZVRH_SUCCESS = "DELETE_ROZVRH_SUCCESS";
export const FINDBY_SKUPINA_ROZVRH_SUCCESS = "FINDBY_SKUPINA_ROZVRH_SUCCESS";
export const FINDBY_TRIEDY_ROZVRH_SUCCESS = "FINDBY_TRIEDY_ROZVRH_SUCCESS";
export const FINDBY_UCITEL_ROZVRH_SUCCESS = "FINDBY_UCITEL_ROZVRH_SUCCESS";
export const FINDBY_VYUCOVANIE_CAS_ROZVRH_SUCCESS = "FINDBY_VYUCOVANIE_CAS_ROZVRH_SUCCESS";
export const GET_ROZVRH_SUCCESS = "GET_ROZVRH_SUCCESS";
export const LIST_ROZVRH_SUCCESS = "LIST_ROZVRH_SUCCESS";
export const UPDATE_ROZVRH_SUCCESS = "UPDATE_ROZVRH_SUCCESS";

// SKOLA
export const CREATE_SKOLA_SUCCESS = "CREATE_SKOLA_SUCCESS";
export const DELETE_SKOLA_SUCCESS = "DELETE_SKOLA_SUCCESS";
export const GET_SKOLA_SUCCESS = "GET_SKOLA_SUCCESS";
export const LIST_SKOLA_SUCCESS = "LIST_SKOLA_SUCCESS";
export const UPDATE_SKOLA_SUCCESS = "UPDATE_SKOLA_SUCCESS";

// SKUPINA
export const CREATE_SKUPINA_SUCCESS = "CREATE_SKUPINA_SUCCESS";
export const DELETE_SKUPINA_SUCCESS = "DELETE_SKUPINA_SUCCESS";
export const FINDBY_TRIEDY_SKUPINA_SUCCESS = "FINDBY_TRIEDY_SKUPINA_SUCCESS";
export const FINDBY_UCITEL_SKUPINA_SUCCESS = "FINDBY_UCITEL_SKUPINA_SUCCESS";
export const GET_SKUPINA_SUCCESS = "GET_SKUPINA_SUCCESS";
export const LIST_SKUPINA_SUCCESS = "LIST_SKUPINA_SUCCESS";
export const UPDATE_SKUPINA_SUCCESS = "UPDATE_SKUPINA_SUCCESS";

// SPRAVY_ARCHIV
export const CREATE_SPRAVY_ARCHIV_SUCCESS = "CREATE_SPRAVY_ARCHIV_SUCCESS";
export const DELETE_SPRAVY_ARCHIV_SUCCESS = "DELETE_SPRAVY_ARCHIV_SUCCESS";
export const FINDBY_SPRAVY_SKUPINA_SPRAVY_ARCHIV_SUCCESS = "FINDBY_SPRAVY_SKUPINA_SPRAVY_ARCHIV_SUCCESS";
export const FINDBY_SPRAVY_UZIVATELIA_SPRAVY_ARCHIV_SUCCESS = "FINDBY_SPRAVY_UZIVATELIA_SPRAVY_ARCHIV_SUCCESS";
export const GET_SPRAVY_ARCHIV_SUCCESS = "GET_SPRAVY_ARCHIV_SUCCESS";
export const LIST_SPRAVY_ARCHIV_SUCCESS = "LIST_SPRAVY_ARCHIV_SUCCESS";
export const UPDATE_SPRAVY_ARCHIV_SUCCESS = "UPDATE_SPRAVY_ARCHIV_SUCCESS";

// SPRAVY_SKUPINY
export const CREATE_SPRAVY_SKUPINY_SUCCESS = "CREATE_SPRAVY_SKUPINY_SUCCESS";
export const DELETE_SPRAVY_SKUPINY_SUCCESS = "DELETE_SPRAVY_SKUPINY_SUCCESS";
export const FINDBY_SKUPINA_SPRAVY_SKUPINY_SUCCESS = "FINDBY_SKUPINA_SPRAVY_SKUPINY_SUCCESS";
export const GET_SPRAVY_SKUPINY_SUCCESS = "GET_SPRAVY_SKUPINY_SUCCESS";
export const LIST_SPRAVY_SKUPINY_SUCCESS = "LIST_SPRAVY_SKUPINY_SUCCESS";
export const UPDATE_SPRAVY_SKUPINY_SUCCESS = "UPDATE_SPRAVY_SKUPINY_SUCCESS";

// SPRAVY_UZIVATELIA
export const CREATE_SPRAVY_UZIVATELIA_SUCCESS = "CREATE_SPRAVY_UZIVATELIA_SUCCESS";
export const DELETE_SPRAVY_UZIVATELIA_SUCCESS = "DELETE_SPRAVY_UZIVATELIA_SUCCESS";
export const GET_SPRAVY_UZIVATELIA_SUCCESS = "GET_SPRAVY_UZIVATELIA_SUCCESS";
export const LIST_SPRAVY_UZIVATELIA_SUCCESS = "LIST_SPRAVY_UZIVATELIA_SUCCESS";
export const UPDATE_SPRAVY_UZIVATELIA_SUCCESS = "UPDATE_SPRAVY_UZIVATELIA_SUCCESS";

// STUDENT
export const CREATE_STUDENT_SUCCESS = "CREATE_STUDENT_SUCCESS";
export const DELETE_STUDENT_SUCCESS = "DELETE_STUDENT_SUCCESS";
export const FINDBY_DOCHAZKA_STUDENT_SUCCESS = "FINDBY_DOCHAZKA_STUDENT_SUCCESS";
export const FINDBY_ODBORY_STUDENT_SUCCESS = "FINDBY_ODBORY_STUDENT_SUCCESS";
export const FINDBY_RODICIA_STUDENT_SUCCESS = "FINDBY_RODICIA_STUDENT_SUCCESS";
export const FINDBY_SKUPINA_STUDENT_SUCCESS = "FINDBY_SKUPINA_STUDENT_SUCCESS";
export const FINDBY_TRIEDY_STUDENT_SUCCESS = "FINDBY_TRIEDY_STUDENT_SUCCESS";
export const FINDBY_UZIVATEL_STUDENT_SUCCESS = "FINDBY_UZIVATEL_STUDENT_SUCCESS";
export const GET_STUDENT_SUCCESS = "GET_STUDENT_SUCCESS";
export const LIST_STUDENT_SUCCESS = "LIST_STUDENT_SUCCESS";
export const UPDATE_STUDENT_SUCCESS = "UPDATE_STUDENT_SUCCESS";

// TRIEDY
export const CREATE_TRIEDY_SUCCESS = "CREATE_TRIEDY_SUCCESS";
export const DELETE_TRIEDY_SUCCESS = "DELETE_TRIEDY_SUCCESS";
export const FINDBY_ODBORY_TRIEDY_SUCCESS = "FINDBY_ODBORY_TRIEDY_SUCCESS";
export const FINDBY_SKUPINA_TRIEDY_SUCCESS = "FINDBY_SKUPINA_TRIEDY_SUCCESS";
export const FINDBY_UCITEL_TRIEDY_SUCCESS = "FINDBY_UCITEL_TRIEDY_SUCCESS";
export const GET_TRIEDY_SUCCESS = "GET_TRIEDY_SUCCESS";
export const LIST_TRIEDY_SUCCESS = "LIST_TRIEDY_SUCCESS";
export const UPDATE_TRIEDY_SUCCESS = "UPDATE_TRIEDY_SUCCESS";

// UCITEL
export const CREATE_UCITEL_SUCCESS = "CREATE_UCITEL_SUCCESS";
export const DELETE_UCITEL_SUCCESS = "DELETE_UCITEL_SUCCESS";
export const FINDBY_TRIEDY_UCITEL_SUCCESS = "FINDBY_TRIEDY_UCITEL_SUCCESS";
export const FINDBY_UZIVATEL_UCITEL_SUCCESS = "FINDBY_UZIVATEL_UCITEL_SUCCESS";
export const GET_UCITEL_SUCCESS = "GET_UCITEL_SUCCESS";
export const LIST_UCITEL_SUCCESS = "LIST_UCITEL_SUCCESS";
export const UPDATE_UCITEL_SUCCESS = "UPDATE_UCITEL_SUCCESS";

// UDALOST
export const CREATE_UDALOST_SUCCESS = "CREATE_UDALOST_SUCCESS";
export const DELETE_UDALOST_SUCCESS = "DELETE_UDALOST_SUCCESS";
export const GET_UDALOST_SUCCESS = "GET_UDALOST_SUCCESS";
export const LIST_UDALOST_SUCCESS = "LIST_UDALOST_SUCCESS";
export const UPDATE_UDALOST_SUCCESS = "UPDATE_UDALOST_SUCCESS";

// UZIVATEL
export const CREATE_UZIVATEL_SUCCESS = "CREATE_UZIVATEL_SUCCESS";
export const DELETE_UZIVATEL_SUCCESS = "DELETE_UZIVATEL_SUCCESS";
export const GET_UZIVATEL_SUCCESS = "GET_UZIVATEL_SUCCESS";
export const LIST_UZIVATEL_SUCCESS = "LIST_UZIVATEL_SUCCESS";
export const UPDATE_UZIVATEL_SUCCESS = "UPDATE_UZIVATEL_SUCCESS";

// VYUCOVANIE_CAS
export const CREATE_VYUCOVANIE_CAS_SUCCESS = "CREATE_VYUCOVANIE_CAS_SUCCESS";
export const DELETE_VYUCOVANIE_CAS_SUCCESS = "DELETE_VYUCOVANIE_CAS_SUCCESS";
export const GET_VYUCOVANIE_CAS_SUCCESS = "GET_VYUCOVANIE_CAS_SUCCESS";
export const LIST_VYUCOVANIE_CAS_SUCCESS = "LIST_VYUCOVANIE_CAS_SUCCESS";
export const UPDATE_VYUCOVANIE_CAS_SUCCESS = "UPDATE_VYUCOVANIE_CAS_SUCCESS";

// ZADANIA
export const CREATE_ZADANIA_SUCCESS = "CREATE_ZADANIA_SUCCESS";
export const DELETE_ZADANIA_SUCCESS = "DELETE_ZADANIA_SUCCESS";
export const FINDBY_SKUPINA_ZADANIA_SUCCESS = "FINDBY_SKUPINA_ZADANIA_SUCCESS";
export const FINDBY_TRIEDY_ZADANIA_SUCCESS = "FINDBY_TRIEDY_ZADANIA_SUCCESS";
export const GET_ZADANIA_SUCCESS = "GET_ZADANIA_SUCCESS";
export const LIST_ZADANIA_SUCCESS = "LIST_ZADANIA_SUCCESS";
export const OVERENIE_ZADANIA_SUCCESS = "OVERENIE_ZADANIA_SUCCESS";
export const UPDATE_ZADANIA_SUCCESS = "UPDATE_ZADANIA_SUCCESS";

// ZNAMKY
export const CREATE_ZNAMKY_SUCCESS = "CREATE_ZNAMKY_SUCCESS";
export const DELETE_ZNAMKY_SUCCESS = "DELETE_ZNAMKY_SUCCESS";
export const GET_ZNAMKY_SUCCESS = "GET_ZNAMKY_SUCCESS";
export const LIST_ZNAMKY_SUCCESS = "LIST_ZNAMKY_SUCCESS";
export const UPDATE_ZNAMKY_SUCCESS = "UPDATE_ZNAMKY_SUCCESS";

// END CRUD CONSTANTS

// USER
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const CHANGE_PASSWORD_SUCCESS = "CHANGE_PASSWORD_SUCCESS";
export const CHANGE_PASSWORD_ADMIN_SUCCESS = "CHANGE_PASSWORD_ADMIN_SUCCESS";
